### ISSUE TITLE
app/Services/ProfileBuilder.php contains an extra "," causing an error

### ISSUE THREAD

**Issue by wbovela** [laravel-enso/core#113]
This is a bug

* [X ] Are you running the latest version?
* [X ] Are you reporting to the correct repository?
* [X ] Did you check the documentation?
* [X ] Did you perform a cursory search?

### Description
Loading the user profile causes a server side error

" "message": "syntax error, unexpected ')'",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/home/vagrant/oxygen4/vendor/laravel-enso/core/src/app/Services/ProfileBuilder.php",
    "line": 26,
"

Steps to reproduce:
Load user profile

### Expected behavior
No error

### Actual behavior
error

Solution:
remove comma

**Comment by aocneanu** [comment]
You should upgrade to php 7.3. You can also make a PR.

**Comment by wbovela** [comment]
Got it. Thanks.
