### ISSUE TITLE
mix-manifest.json not found after refresh

### ISSUE THREAD

**Issue by wbovela** [laravel-enso/core#119]
This is an issue

### Prerequisites
* [ ] Are you running the latest version? --> No, I am in the process of upgrading to 3.7.2
* [X ] Are you reporting to the correct repository?
* [X ] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
I can load the User table, for instance without a problem. But when I refresh the page I get an error message "The Mix manifest does not exist."
I have tracked this down to the file core/src/resources/views/index.blade.php containing references to the helper mix() which uses the Mix::class in laravel/framework/src/Illuminate/Foudation/Mix.php which references the mix-manifest.json file which  no longer exists.

### Steps to Reproduce
1. load User table
2. refresh the page

### Expected behavior
the user table
(please note that I can not reproduce this in the online version of Enso. It started occurring after the upgrade to 3.7.2)

### Actual behavior
an error message saying that the mix-manifest.json file is missing

**Comment by aocneanu** [comment]
The core `index.blade.php` is a left over, the latest push on core removes it.

We will release in a few days 3.7.4 and the changelog will cover this as well but I guess you can already do the following for yourself

After completing the steps in #79 do the following

### update the production file location in client/vue.config.js
```js
main: {
    entry: 'src/js/enso.js',
    minify: false,
    filename: process.env.NODE_ENV === 'production'
        ? '../resources/views/index.blade.php'
        : './index.html',
    template: process.env.NODE_ENV === 'production'
        ? '../vendor/laravel-enso/core/stubs/production-index.blade.stub'
        : '../vendor/laravel-enso/core/stubs/development-index.stub',
},
```

### update the default route in routes/web.php
```php
Route::view('/{any}', 'index')->where('any', '.*');
```

### add in the root .gitignore under the local files
```bash
resources/views/index.blade.php
```

### update client/babel.config.js to
```js
module.exports = {
    presets: [
        '@vue/cli-plugin-babel/preset',
    ],
};
```
### add the --modern flag in client/package.json under build

```json
"build": "rm -rf ../public/{js,themes,themes-rtl,images} && vue-cli-service build --no-clean --modern",
```

**Comment by wbovela** [comment]
Thanks!

**Comment by wbovela** [comment]
I now get the following error:

InvalidArgumentException
View [index] not found.

I think I'm missing a file in resources/views. I've tried copying the old index.blade.php file, but I get an 'Unexpected "<"' error.

**Comment by aocneanu** [comment]
after you update `client/vue.config.js` you need to rebuild the app.

Are you experiencing this in production or locally?

**Comment by wbovela** [comment]
I rebuilt the app, but it does the same.
It's local, not production.
Should there be an index.blade.php in resources/views?

**Comment by aocneanu** [comment]
are you sure that you updated this in `vue.config.js`

![image](https://user-images.githubusercontent.com/16073274/70719155-236d7880-1cfa-11ea-941d-23b2880454cc.png)

**Comment by wbovela** [comment]
Yes. I hope the screen shot below shows...
<img width="948" alt="Screen Shot 2019-12-12 at 15 20 54" src="https://user-images.githubusercontent.com/8072835/70719846-0da88500-1cf3-11ea-92ce-19c052113b95.png">

**Comment by aocneanu** [comment]
on `yarn build` the file will be there the same it was with the previous configuration when we had it under vendor. For sure you have a typo somewhere.

**Comment by wbovela** [comment]
I'll keep looking. Thanks for your help.
