### ISSUE TITLE
Applying Multiple CustomFilter

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/core#167]
This is  a **question**.

### Description
Where can I find this implementation Users filters for Roles and Active (both):

![image](https://user-images.githubusercontent.com/16973022/92612176-4ac19800-f2c2-11ea-9fc8-fe5659dd831f.png)

I've checked out the enso/core repo and I can only find the implementation for :

```json
"filters": [{
        "label": "Role",
        "data": "users.role_id",
        "type": "select",
        "value": [],
        "route": "system.roles.options",
        "multiple": true
    }],
```

I'm more instersted how does one combine 2 filters together - how can I use multiple custom filters ? Like:

```php
public function filterApplies(Obj $params): bool
    {
        return optional($params->get('user'))->filled('is_active') ?? false || optional($params->get('user'))->filled('is_locked') ?? false;
    }

    public function filter(Builder $query, Obj $params)
    {
        return $query->when(
            $params->get('user')->get('is_active'),
            fn($query) => $query->where('is_active', '=', 1),
            fn($query) => $query->where('is_active', '=', 0)
        )->when(
            $params->get('user')->get('is_locked'),
            fn($query) => $query->where('is_locked', '=', 1),
            fn($query) => $query->where('is_locked', '=', 0));
    }
```

Thank you,

**Comment by aocneanu** [comment]
You missed [this](https://github.com/laravel-enso/core/blob/master/src/Tables/Templates/users.json#L95)

Most columns will be filterable automatically.

Only custom scenarios need the "filters" property in template.

**Comment by robbykrlos** [comment]
> You missed [this](https://github.com/laravel-enso/core/blob/master/src/Tables/Templates/users.json#L95)
> 
> Most columns will be filterable automatically.
> 
> Only custom scenarios need the "filters" property in template.

Thanks for this, yes, I missed that part. But it seems that I still need to merge 2 custom filters because my is_active and is_locked is represented by a custom slot that displays a custom icon, therefore the json configuraiton is not actually pointing tot the db column, so default filters will not work in this situation.

I'm still tweaking and playing around with the "->when" conditions to combine 2 conditions. If you have any suggestions I'll be glad to hear them, if not, thanks for the help - ticket can be closed.

**Comment by aocneanu** [comment]
@robbykrlos shoot me an email when you have the time, I want to ask you something.

**Comment by robbykrlos** [comment]
I still think there is an issue with the custom filters. I tried to debug a bit and found that if more then 1 custom filter is used, the last one is not "remembered". Here's my example:

I have 2 custom filters:
```json
"filters": [
        {
            "label": "Is Maintenance",
            "data": "cluster.is_maintenance",
            "type": "boolean",
            "custom": true,
            "value": false
        },
        {
            "label": "Is Active",
            "data": "cluster.is_active",
            "type": "boolean",
            "custom": true,
            "value": false
        }
    ],
```

And trying to see what happens in my Table calss:
```php
class ClusterTable implements Table, CustomFilter
{

...
public function filterApplies(Obj $params): bool
    {
//forced assumption that both custom filter are applied
        return true;
    }
...
public function filter(Builder $query, Obj $params)
    {
//forced assumption that both custom filter are applied
$query->where('is_maintenance', $params->get('cluster')->get('is_maintenance'))
            ->where('is_active', $params->get('cluster')->get('is_active'));

var_dump($params, $query->toSql());
```

var_dump output
```
object(LaravelEnso\Helpers\Services\Obj)#1633 (1) {
  ["items":protected]=>
  array(1) {
    ["cluster"]=>
    object(LaravelEnso\Helpers\Services\Obj)#1643 (1) {
      ["items":protected]=>
      array(1) {
        ["is_active"]=>
        bool(true)
      }
    }
  }
}

select ...
...
where ((`clusters`.`version` LIKE ?)) and `is_maintenance` is null and `is_active` = ? and `clusters`.`deleted_at` is null"
```

Here is how the UI looks
![image](https://user-images.githubusercontent.com/16973022/92896971-7d37d600-f425-11ea-87f2-5ddc013d28bd.png)

The version filter is one which is not custom and set as you mentioned above : ``You missed this``
```json
"meta": [
                "boolean",
                "filterable"
            ]
```

As you can see the ``is_maintenance`` custom filter value is not set in the query where clause, because it's not present in the $params collection, although the UI, and the tableData request contains the right details:

![image](https://user-images.githubusercontent.com/16973022/92898089-62b22c80-f426-11ea-9336-ce5c4c2295e8.png)

Some strangeness what I observer is that the filter method is called twice, because it outputs twice the $params and query sql, and both times the output is the same.  Initially I believed this is based on the number of custom Filters I add, but this is not related.

Unfortunately I do not have much time to look under the hood this time to clarify where the params value is lost for ``is_maintenance``, so I'm reaching again to you in case you have some out of the box ideas.
Thanks.

**Comment by raftx24** [comment]
Hi @robbykrlos 
I checked it and I guess you are right.
pleas check https://github.com/laravel-enso/tables/pull/222
thank you
