### ISSUE TITLE
Restrict non admin and supervisor from performing actions and viewing data

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/core#168]
This is  a ** feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
I wrote code to restrict non admins in my fork for my application. So if you aren't an admin you can only see your own user and manipulate it. You can't touch anyone else's account. Would this be of interest? I don't know if I wrote it the best way so proposing the idea.

**Comment by aocneanu** [comment]
add here a link to the policy file / auth file

**Comment by curtisdelicata** [comment]
I didn't think of doing a policy. I modified the controllers and table. Maybe I did it wrong.

**Comment by curtisdelicata** [comment]
Link is here: https://github.com/genealogiawebsite/core
