### ISSUE TITLE
Remaining known misc issues

### ISSUE THREAD

**Issue by gandesc** [laravel-enso/Core#20]
* [x] permissions -> create resource, during the process, set a default permission description, alongside the generated name.
* [x] we should have tutorials for the core pages
* [ ] for the role creation/edit form, set a description tooltip for the implicit menu option
* [x] when a new user is created, if it's created as disabled, a password reset email should not be sent

**Comment by aocneanu** [comment]
> default supervisor role can be removed
No need. The migration adds the default permissions for the supervisor. You should test it..

> tooltips for the custom DT buttons
I'm not sure that we want this. Maybe we will implement it with an option to turn the tooltips on/off.

> TBD if we should have tutorials for the various core pages
We should definitely have tutorials for every page in Enso.  We should do this before putting the demo up.

> for the role creation/edit form, set a description tooltip for the implicit menu option
tbd

>  when a new user is created, if it's created as disabled, a password reset email should not be sent
Before doing that we must decide on a new activation flow for this situation or else the new user may never know that he has a new account. The way it works now, if the disabled user gets a set/reset password email and cannot set his password, he can contact the application administrator.
