### ISSUE TITLE
SQL syntax error in PostgresSQL

### ISSUE THREAD

**Issue by nnnms** [laravel-enso/Core#33]
Where:

at LaravelEnso\Core\app\Http\Controllers\User\UserTableController, line 19

What:

1) PostgreSQL returns non-escaped aliases in lowercase: dtRowId -> dtrowid
2) PostgreSQL requires AS keyword for column aliases

Possible fix:

escape dtRowId with double quotes and add missing AS keywords.

This issue affects all the modules with 'select something as dtRowId' sql. This solution working, but isn't best, because all the logic with dtRowId is plugin-specific and the decision which column to use should be taken on the frontend.

**Comment by aocneanu** [comment]
Sorry about that. We didn’t had the opportunity to test Enso with PostgreSQL until now. If you want, you can make a PR for this.

Cheers

**Comment by aocneanu** [comment]
closed with 87df968
