### ISSUE TITLE
Possibility to add own icons to navbar

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Core#37]
I added icons for new menu items to `resources/assets/js/pages/layout/sidebar/icons/enso.js`
After publishing this file gets overwritten by your default file.

See:
![screenshot 2018-01-31 17 01 48](https://user-images.githubusercontent.com/7204559/35633040-9bec4d82-06a8-11e8-8ee1-1a9f31846246.png)

Is there a possibility to add own icons without getting them overwritten everytime?

**Comment by aocneanu** [comment]
In `assest/js/pages/layout/sidebar/icons` you will find three files:

- `enso.js` where the defaults are, this gets overwritten at updates.
- `app.js` comes empty, that's the place for adding icons for the new menus.
- `index.js` responsible for including both of the above.

**Comment by mauthi** [comment]
Perfect. Did I miss this in documentation/changelog - of if not, I think you should add this.

But, at the moment the app.js gets overwritten by publishing items - see:
![screenshot 2018-02-01 13 52 38](https://user-images.githubusercontent.com/7204559/35679403-31c1babe-0757-11e8-8923-558fe0ae2a9c.png)

Maybe we can think about the same split for languages? But that's another topic...

**Comment by cosimolemma** [comment]
It works like a charm. Thanks a lot!
