### ISSUE TITLE
Passwort reset link contains 2 slashes

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Core#47]
This is  a bug.

## Description
Passwort reset link contains 2 slashes

### Steps to Reproduce
Go to login page
Reset password
Enter a valid email address
`php artisan queue:work`
Check link in mail

### Expected behavior
xxx.com/password/reset/xxxx

### Actual behavior
xxx.com//password/reset/xxxx

**Comment by aocneanu** [comment]
This is an password reset link from laravel-enso.com

`https://www.laravel-enso.com/password/reset/a07e38...`

Maybe you modified the notification template?

How does your `APP_URL` key look in you `.env` ?

**Comment by mauthi** [comment]
Sorry, had an slash at the end of my `APP_URL`
