### ISSUE TITLE
Right handed sidebar: Div. Issues

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Core#50]
This is  a feature request.

### Description
At the moment we have no possibility to hide theme switch and language switch if only one option is available.

Other possible improvements (if needed I can create seperate issues for this):
- Use default language for new users from config
- Make default theme configurable (if clean is not available)
- Make theme dropdown configurable
- Possibility to hide tutorials button if not needed

**Comment by aocneanu** [comment]
All make sense, please open dedicated issues, all on core

**Comment by mauthi** [comment]
Done!
