### ISSUE TITLE
Right handed sidebar: Hide select fields if only one option is available (languages, themes)

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Core#51]
This is  a feature request.

### Description
At the moment we have no possibility to hide theme switch and language switch if only one option is available.

### Steps to Reproduce
Disable all themes/languages except one

### Expected behavior
Select fields in right handed sidebar should be hidden because not needed

### Actual behavior
Select fields in right handed sidebar are visible

**Comment by aocneanu** [comment]
For new user's default theme, update [here](https://github.com/laravel-enso/Enso/blob/master/resources/preferences.json#L6)
