### ISSUE TITLE
Use default language for new users from config

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Core#52]
This is  a feature request.

### Description
New users should use language from `config.app.locale`

### Steps to Reproduce
Set config value to <> en
create new user
login with new user

### Expected behavior
New user should have language of `config.app.locale`

### Actual behavior
New user has `en` as default language

**Comment by aocneanu** [comment]
It seems that there is already something in place for this.

I don't think that it's a good time to change things in this area, at least until we will have a proper preferences module / flow.

So for now just set the value that you desire [here](https://github.com/laravel-enso/Enso/blob/master/resources/preferences.json#L3)
