### ISSUE TITLE
Make theme list and default theme configurable

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Core#53]
This is  a feature request.

### Description
Make default theme configurable (if clean is not available)
Make theme dropdown configurable

### Steps to Reproduce
create new user
login with new user

### Expected behavior
New user should have language of `config.enso.themes.default_theme` (new config needed)
Only themes of `config.enso.themes` are shown in select field in right handed sidebar.

### Actual behavior
New users have clean as theme selected
All themes are shown

**Comment by aocneanu** [comment]
For new user's default theme, update [here](https://github.com/laravel-enso/Enso/blob/master/resources/preferences.json#L6)

**Comment by mauthi** [comment]
what's the source for themes for theme selector?
comment them in `config/enso/themes.php` does not help
