### ISSUE TITLE
Right handed sidebar: Possibility to hide tutorials button if not needed

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Core#54]
This is  a feature request.

### Description
Create possibility to hide tutorials button if not needed

### Expected behavior
Tutorials button should be visible based on config

### Actual behavior
Tutorials button is visible.

**Comment by aocneanu** [comment]
Now we have available a new global helper: `canAccess`. We can use this to show/hide elements in the FE based on the BE permissions.

@gandesc please update the docs.
