### ISSUE TITLE
Mail template

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Core#56]
This is  a feature request.

### Description
At the moment mail templates are the default of Laravel.
Maybe we can think about something to make them more beautiful (colours of theme, add logo)

### Steps to Reproduce
n.a.

### Expected behavior
n.a.

### Actual behavior
n.a.

**Comment by gandesc** [comment]
this is implemented with the 1f94fbffd5fac4da8f95bb4b34373e6e606b4a8e commit.

As examples, take a look at
* CommentTagNotification
* resources/views/emails/*

all within the core package.

After updating to the latest versions of core/vuedatatables/commentsmanager, all core enso notifications will be using the latest templates & mechanism.

The following artisan command is available for publishing the related views and image assets: `php artisan vendor:publish --tag=email-templates` and should be run after update.

Also, a `npm run dev` is needed to publish the image resources.
