### ISSUE TITLE
Multi-owner/role support

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Core#66]
This is  a **feature request**.

### Description
When dealing with multiple "owners"(groups/companies/...) the need quickly arrises to need certain users with multiple owners. Esp. when tying in with AD (where the user table (can) get provisioned by it; but owner_id & role_id are blocking that insertion)

**Comment by aocneanu** [comment]
Owners are role collections used to limit the user role to a certain collection.

In some simple cases you can extend Owners into some other entity, like Companies, like your example. I don't see how a user should belong to two companies but that's another thing...

If things get complicated you should make a dedicated Companies structure, and if it makes sene map Owners to Companies.

For instance, owners can be: comercial, technical, management, training, and you can have companies which have trainers (or a training dep) and companies that don't.

**Comment by jlsjonas** [comment]
99% of our users do fine with just 1 owner; the issue is those select few (& the mapping that can't happen via our AD)

just realized we could likely abuse the impersonation system for those users; however dealing with the user profile not showing up while I was testing 😅  (doing a fresh upgrade to the latest enso now; as quite a lot changed recently so might've updated to a _bad_ version)

**Comment by aocneanu** [comment]
I believe that we can close this.

**Comment by jlsjonas** [comment]
There's a workaround possible indeed; although I'd still consider it for a future refactor.
