### ISSUE TITLE
localizations key collection requests are broken (config get's nullified)

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Core#76]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

axios.js plugin breaks localization's _key capturing_

### Steps to Reproduce
1. Log in on the framework
2. turn on key collection
3. notice errors in console

### Expected behavior

Keys to be generated

### Actual behavior

`vendor/laravel-enso/core/src/resources/js/modules/enso/plugins/axios.js` (or it's published counterpart)
returns false to the config in certain cases; this causes axios to break. (see https://github.com/axios/axios/issues/1497)

**Comment by aocneanu** [comment]
For the last couple of days we just translated a whole app without issues, so it must be something else.

The interceptor should block only identical requests (same payload), which should not be a problem.

@dorincarsin did you encounter any console errors during the translation process?

**Comment by dorincarsin** [comment]
i had console errors, pasted below, but the key collector worked, i found them in localisation.
![image](https://user-images.githubusercontent.com/15261339/47222285-07549c80-d3bf-11e8-9fe2-b002a99896c5.png)

**Comment by aocneanu** [comment]
decided to remove the experimental "feature" of filtering repetitive and possibly unwanted requests and leave this concern on the dev side.

@gandesc
