### ISSUE TITLE
Make router push expand corresponding menu item

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Core#80]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
I'd suggest making the menu expand when a router.push (, router-link or similar event) gets triggered.

### Steps to Reproduce
1. add a router.push to an existing route somewhere
2. click on it (with related menu collapsed)

### Expected behavior
menu to expand, highlighting the active item

### Actual behavior
menu stays collapsed, hiding the active element

### Example Use Case

Dashboard links to certain pages

**Comment by jlsjonas** [comment]
Note that `this.checkActiveChildren(this.menus);` is responsible for the expansion upon pageload. calling it (via debug) does match expected behavior highlighted above

**Comment by aocneanu** [comment]
As a plus now it also auto collapses expanded menu with no selection
