### ISSUE TITLE
Login model/relation missing cascade/ignore

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Core#81]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Deleting a user is impossible even if the only action he took was logging in
![image](https://user-images.githubusercontent.com/932193/48256538-413e1f00-e410-11e8-9436-29703af1603f.png)

### Expected behavior

Being able to delete a user that did nothing but logging in

### Actual behavior

Foreign key constraint

**Comment by aocneanu** [comment]
This is not a bug, again, it's Enso's business logic.

Create an observer for the user model and cleanup what you need prior to it's deletion.

**Comment by jlsjonas** [comment]
Thought it was a remnant of the cleanup from recently as I never encountered it before.

As logins can't be managed from the interface (and are relatively insignificant) it definitely looked like a bug

👍

**Comment by aocneanu** [comment]
A user id can propagate in many places. You should never delete the user with a raw query. Use the delete() method from the model ;)

https://github.com/laravel-enso/Core/blob/master/src/app/Models/User.php#L151

**Comment by jlsjonas** [comment]
I used delete(); that was the error that it was generating.
