### ISSUE TITLE
Can't logout when already logged out (session expiry in backend)

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Core#82]
This is a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

When trying to log out, the api responds with a 419 (unknown status) and the SPA _crashes_ (uncaught _error_ `Request failed with status code 419`)

### Steps to Reproduce
1. Log in to the SPA; ensure you're on a page that has a logout button
2. wait for session expiry or log that session out from the backend only
3. click the logout button

### Expected behavior

Get redirected to the login page

### Actual behavior

nothing happens (console has errors mentioned above)

**Comment by aocneanu** [comment]
This is a bug and your the sarcasm is misplaced here.

Lately I'm oscillating between focusing on the constructive contribution that you are having on Enso and banning you from the repo for all the other reasons that I mentioned over time.
