### ISSUE TITLE
Use browser language (if supported) by default

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Core#84]
This is  a ** feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Use accept_language header to set default language if supported ([helpful SO resource](https://stackoverflow.com/questions/36986236/how-to-detect-language-preference-in-laravel-5))

### Steps to Reproduce
N/A

### Expected behavior

when visiting the site (not logged in yet) the GuestState should check the accept_language header to know the prefered language; and respect it if possible.

### Actual behavior

default language of english (or whatever's set in preferences) is used

### Use Case
Not all users speak the same language

**Comment by jlsjonas** [comment]
this should be solved by adding the following in `GuestState.php`'s `toResponse` function
```php
        $languages = Language::active()
            ->pluck('name');
        $prefferedLanguage = $request->getPreferredLanguage($languages->all());
        app()->setLocale($prefferedLanguage);
```


However, it seems that for some reason; although (if you inspect the vue state) everything only shows translated strings, and the global language preference also matches the language; it's still showing the english version 🤔

**Comment by aocneanu** [comment]
Starting now, the localisation in Auth uses the users preference if he previously set one (localStorage) or the `config(app.locale) value.

**Comment by aocneanu** [comment]
Because it's not needed and it does not provide extra value. Enso is for closed / private apps. You can set a default locale that will work for everybody on the first login (eg, English). After login each user will be able to customize the app and that's it.

If I go in Holland and log into the app from a friends PC having the auth in Deutch would be awkward.

**Comment by jlsjonas** [comment]
True, however as it's a closed system, we actually have our computers set up to the correct language already (and have don't have a common language shared amongst everyone directly) ; but we'll just customize it on our end ;)

It's actually not applying the language correctly though:

If I select a language and log out again the language is applied; but if you refresh the page you just get the default language
- preferences/global/lang matches up
- localisation/i18n contains an object with the key matching up to the lang above
- [ ] (likely the cause) language array in localisation is empty
![image](https://user-images.githubusercontent.com/932193/48896399-cfba9380-ee47-11e8-99d2-d70aa653e458.png)

**Comment by aocneanu** [comment]
look in the network tab and see how the request is made. 

Is it `meta?locale=xx` ?

**Comment by jlsjonas** [comment]
I got some new info...
![image](https://user-images.githubusercontent.com/932193/49091729-b444f380-f260-11e8-9f29-7403ff469f76.png)
For some reason the preferences/lang getter doesn't get re-triggered when the language is actually set. and it's initial value is undefined because the data isn't there yet.

I've temporarily _hacked_ around it (actually a recommended practise, [depending on who you ask](https://codeburst.io/vuex-getters-are-great-but-dont-overuse-them-9c946689b414)) by just getting the lang directly from the state 

i.e.: in `resources/js/store/localisation.js`
replace `const lang = rootGetters['preferences/lang'];`
with
```js
const lang = rootGetters['preferences/lang']
            || ((rootState.preferences && rootState.preferences.global)
                ? rootState.preferences.global.lang : null);
```
(ternary operator just in case, during testing I didn't need it)
