### ISSUE TITLE
Support "return url" when not logged in

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/core#86]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

When following a (browser) bookmark, clicking a link that's sent to you, having an actionable notification, ...; currently if you're not logged in you'll just be redirected to the login page & subsequently the dashboard (or whatever you set as primary page)

I believe it would be a great addition to keep track of the link that redirected you to login, and return to it in case it's a platform url (known route).

This would also allow using the action buttons for emails in a sensible way (when coming from an email there's a high chance you're not logged in)

### Steps to Reproduce
1. Follow a known-good url in the app, for example [user #1 on laravel-enso.com](https://www.laravel-enso.com/administration/users/1) (when not logged in)
2. Log in after being redirected to `/login`
3. note that you're redirected to the dashboard

**Comment by aocneanu** [comment]
[closed](https://github.com/enso-ui/ui/commit/a472a423bf5f22c2f254daf28fa924f545b1bd63)
