### ISSUE TITLE
Can't make app work with BowserSync or other tools

### ISSUE THREAD

**Issue by gagishmagi** [laravel-enso/Core#94]
This is  a **bug | feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

I am not able to use browsersync or live server or live reload.
After fixing the issue with CORS which doesn't like that the headers:
x-requested-with, x-csrf-token by minimum

### Steps to Reproduce

1. Installed browsersync and browsersync webpack modules with npm
2. (optional) add a plugin to favorite IDE
3. Run the command : npm run watch
4. Created CORS middleware and use it globally or only for api routes...
5. (optional) Or  install some laravel cors package.
6. Allow CORS domains , methods, headers and additional two ones: x-requested-with, x-csrf-token also can allow x-xsrf-token
for angular apps.
7. Try to go to localhost:PORT(default nodejs 3000) you will get a login page.
8. Try to login with Admin account or any other and you will be Unauthorized and redirected back to login.

### Expected behavior

After successful login on localhost:3000 redirect to home page. 

### Actual behavior

After successful login on localhost:3000 get "401 Unauthorized" and redirect to login.  

Thank you for your help.

**Comment by aocneanu** [comment]
I have 0 experience with BrowserSync.

**Comment by gagishmagi** [comment]
:-(

**Comment by gagishmagi** [comment]
It's definitely not an issue with browser sync it's something in the app that has to do with the authorization.
I guess it's just of my understanding of the authorization process in the app.. :-)

**Comment by aocneanu** [comment]
The only additions that Enso makes over Laravel's provided boilerplate is checking that the user is Active and enforcing the password policy. Sorry that I cannot be of more help than that
