### ISSUE TITLE
index.blade.php is used from vendor dir even it is published to resurces folder

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Core#98]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
I have 2 files:
- `resources/views/index.blade.php` AND
- `vendor/laravel-enso/core/src/resources/views/index.blade.php`

I would like to use my view but system takes vendor view every time.
Is this a bug or a feature?
If it's a feature how can I overwrite the initial theme?

### Expected behavior
Overwrite vendor file with local file if a local file exists

### Actual behavior
Vendor file is used

**Comment by aocneanu** [comment]
It's intended to be that way.

Why don't you change the `enso/themes` config.

**Comment by mauthi** [comment]
I already changed the `enso/themes` config but the `vendor/laravel-enso/core/src/resources/views/index.blade.php` uses light theme hardcoded - see Line 6:

`link id="theme" rel="stylesheet" type="text/css" href="/themes/light/bulma.min.css">`

**Comment by aocneanu** [comment]
Ah right. Why don't you place your custom theme in that location?

**Comment by mauthi** [comment]
You mean that I name my custom theme "light" instead of custom name?
Is this a good approach? If somebody would like e.g. that dark theme is default than he must rename dark to light?

**Comment by aocneanu** [comment]
The system is built with support to a light and a dark theme.

If somebody want the dark to be default then in `resources/preferences.json` the default `theme` should be dark instead of light.

**Comment by mauthi** [comment]
OK, i added an own theme with a custom name - everything works fine except for the login screen.

I would need a possibility to overwrite `vendor/laravel-enso/core/src/resources/views/index.blade.php` with a local version, but that's not working?

**Comment by mauthi** [comment]
I thought about this and you are right - I will overwrite light and dark theme local.
