### ISSUE TITLE
Error on users profile page after update to 3.x.x:Error in render: "TypeError: Cannot read property 'map' of null"

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/core#99]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
After opening the profile page (`/administration/users/xx`) of a user I get the following error:
![image](https://user-images.githubusercontent.com/7204559/56416031-f0203a00-628f-11e9-9ccb-d0d8fdea0ed8.png)

Did I miss something during update?
(Everything else worked fine with changelog!! Great work!!!)

**Comment by mauthi** [comment]
Any update here - error still exists?

**Comment by aocneanu** [comment]
Not able to reproduce, but I'll release v.3.3.0 soon anyway. Leave this open until then.

**Comment by aocneanu** [comment]
@mauthi can you test if this still manifests on the laestest version?

**Comment by mauthi** [comment]
Sorry, missed your comment. Will test it now.

**Comment by mauthi** [comment]
Error still exists in 3.3.3

**Comment by aocneanu** [comment]
apparently the problem is in [here](https://github.com/enso-ui/ui/blob/master/src/modules/plugins/date-fns/format.js)

could you add a `console.log` and see what goes wrong?

replace 

```js
export default (date, formatStr = null) => format(
    (typeof date === 'string') ? parseISO(date) : date,
    unicode2PHP(formatStr || store.state.meta.dateFormat),
    { locale: i18n[store.state.preferences.global.lang] },
);
```

with

```js
export default function (date, formatStr = null) {
    format(
        (typeof date === 'string') ? parseISO(date) : date,
        unicode2PHP(formatStr || store.state.meta.dateFormat),
        { locale: i18n[store.state.preferences.global.lang] },
    );
}
```

and see if the 3 params that format is receiving are ok.

**Comment by mauthi** [comment]
I did this and I think I found the problem:

My code:
```
export default function (date, formatStr = null) {
	console.log("date: "+date + " | formatStr: "+formatStr);
	console.log("unicode2PHP: "+unicode2PHP(formatStr || store.state.meta.dateFormat))
	return format(
        (typeof date === 'string') ? parseISO(date) : date,
        unicode2PHP(formatStr || store.state.meta.dateFormat),
        { locale: i18n[store.state.preferences.global.lang] },
    );
}
```

Output:
```
date: 1985-09-11 00:00:00 | formatStr: d.m.Y
unicode2PHP: 
```

Problem is, that `unicode2PHP()` can't handle dots as separator. I tried to fix this but I was not able to do it :( 

If I change formatStr to e.g. `d-m-Y` everything works like expected.

**Comment by mauthi** [comment]
@aocneanu do you have an idea how to solve this? Otherwise I'm going to debug `unicode2PHP()`?

**Comment by aocneanu** [comment]
Didn't had time to look at it. Of course that any help si appreciated :)

**Comment by mauthi** [comment]
OK, I will try my best - but not today... If you find time earlier feel free to solve this (I think you will need 1-2 Minutes :))

**Comment by aocneanu** [comment]
closed with commit to related issue
